### ISSUE TITLE
Unify captions in 4 add-ons

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorerAddons#351]
This enhancement is to unify some captions to avoid duplicates in language file.

1. Use the add-on name as the command for 3 add-ons
![to](https://user-images.githubusercontent.com/34089121/211957532-413d3e3b-11dc-4920-a35b-2c17acef2065.png)

2. Change "View flags" to "View" in "Overlay label" add-on
![ol](https://user-images.githubusercontent.com/34089121/211957608-ca283753-7a2f-4bce-8af8-a76ee999c962.png)

@bblackmoor and @tablacus, please help to make the change. Thanks.

**Comment by bblackmoor** [comment]
I have created a pull request for the first three edits:
https://github.com/tablacus/TablacusExplorerAddons/pull/352

However, I think the fourth edit should be considered more carefully.

I recommend changing this in English to "Enable in views". I think that more accurately describes the purpose of that control.

What do you think?

**Comment by bblackmoor** [comment]
> I think "View" is good enough. Most captions in TE are very simplified so I try to follow this style.

I understand what you are saying. I agree that simple labels are usually best for translation purposes.


> Nevertheless some captions are really overly simplified or vague and cause misunderstanding. I prefer to spend our effort in improving these in the future. You will see when you get familiar with TE.

I understand what you are saying.

It may be helpful if I explain my background. I have worked on international projects before, including projects with translation lookup tables. My native language is English, and I have extensive experience writing documentation and managing translation tables.

The issue here is that, in English, "view" can be a verb ("to view", indicating action) _or_ a noun ("a view", indicating an object). It can even be both in the same sentence, as in "I am viewing the view." (But no one talks like this.)

In this case, both the action ("to view" the label) and the object (the label appears in "a view") could be applied. In many cases, the object is obvious ("open", "edit", "copy"). In such cases, the object may be excluded in English without impairing the meaning. This is not one of those cases: neither the verb nor the object are obvious. In English, we need an action and an object for this setting to be easily understood.

Because "view" is ambiguous in this context, we look at where else that term is used. In this context, "the view" refers to the visual arrangement of the files and folders.

I installed the add-on, and if I understand its purpose correctly, toggling the setting shows or hides the label when the user is displaying the specified "view". Our action is to show or hide. We are "enabling" the color highlight. (There are other words in English for this, but "enable" is the standard one, which most users will immediately recognize.)

So, in English, I recommend "Enable in views".

I hope this explanation has been helpful.

**Comment by ccfs** [comment]
I agree that "Enable in views" is clearer than "View". However, since most TE translators are inactive, currently translated "View flags" will become untranslated. Then I prefer to keep the add-on unchanged.

**Comment by ccfs** [comment]
so the 4 changes are aborted.

**Comment by bblackmoor** [comment]
It looks that way.

**Comment by bblackmoor** [comment]
Maybe if these changes are made singly, rather than grouped together, a problem with one will not prevent the others from being merged.
