### ISSUE TITLE
Sync select - "Extension" option should be ignored for folders

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorerAddons#353]
Folders do not have "extension", but the add-on cannot handle this correctly. @bblackmoor and @tablacus, please help to solve this problem. Thanks.

![ss](https://user-images.githubusercontent.com/34089121/212233179-e7181a46-2cd4-4402-ae27-a2d8ac3608bd.png)
![fl](https://user-images.githubusercontent.com/34089121/212233183-6b23574a-24ae-4616-a50d-56ecaa2ab922.png)

**Comment by bblackmoor** [comment]
I want to make sure that I understand the desired end result.

WHEN a user 
 - clears the "File extension" check box
 - clicks "Select all items that are in the other pane"
Tablacus 
 - selects "folder.v2" as a match, because "folder.*" in pane 1 matches "folder.*" in pane 2

I tested this in my sandbox. My tests show:

1) When "File extension" (NOTE: This is not a clear label in English. Inverting the logic and labeling it "Ignore extension" would be clearer, and more intuitive.) is **selected** (the default):

![image](https://user-images.githubusercontent.com/33701300/212374542-542662e4-00e6-4459-b414-9b11e0439a8d.png)

"TablacusExplorer" and "TablacusExplorerAddons" are selected. "TablacusExplorer.old" is not. This is as expected.

2) When "File extension" (see note above) is **not selected**:

![image](https://user-images.githubusercontent.com/33701300/212375099-ccd898e6-30d7-4fa0-825a-7c542c986efc.png)

"TablacusExplorer", "TablacusExplorer.old", and "TablacusExplorerAddons" are selected.  This is as expected.

**The setting appears to be functioning as expected.**

If I appear to have misunderstood something, please let me know.

**Comment by bblackmoor** [comment]
@tablacus , I have  question about this label:

`<label><input type="checkbox" name="ext" onclick="Addons.InnerSyncSelect.SwitchExt(this)" onchange="Addons.InnerSyncSelect.SwitchExt(this)" checked>{E4F10A3C-49E6-405D-8288-A23BD4EEAA6C} 100|Extension</label>`

Specifically, this:
**`{E4F10A3C-49E6-405D-8288-A23BD4EEAA6C} 100`**

I do not understand why this is here. That should refer to the file extension attribute of a specific file. I do not understand why it is part of the label logic.

**Comment by ccfs** [comment]
"File extension" is the string after the last dot of the name of a FILE. It indicates a file type and the associated application. However FOLDER is a type itself. Anything in the name, including any dot, is the name.

Therefore in my example above, it is correct for "file.v2" but incorrect for "folder.v2".

**Comment by bblackmoor** [comment]
A directory is a unique type of file that contains only the information needed to access files or other directories. The extension is just part of the name. The add-on appears to be function as expected.

**Comment by bblackmoor** [comment]
Besides, what would be the alternative? That the extension is **always** ignored for directories? Even if the extension on a file was somehow different from the extension on a directory (it's not), is that a reason to _remove_ the choice whether to ignore the extension on directories?

**Comment by ccfs** [comment]
What I stated is the Microsoft's definition of "file extension". Of course some people may have a different understanding. Whatever. Users can try ticking or clearing the option to fit their needs.

So we can keep the add-on unchanged. Thanks.
