### ISSUE TITLE
Help:How to disable new tab when using Total Commander Lister Plug-in

### ISSUE THREAD

**Issue by 921j** [tablacus/TablacusExplorerAddons#368]
Every time using Total Commander Lister Plug-in,Tablacus create a new empyt tab, Is there a way or option to disable this tab created?
![2023-09-23_141345](https://github.com/tablacus/TablacusExplorerAddons/assets/29940386/d78839ad-3506-487f-acff-15ff9ca62944)

**Comment by ccfs** [comment]
There is probably not any way to disable the tab.
What do you want to do with the MP4 file?

**Comment by 921j** [comment]
> There is probably not any way to disable the tab.可能没有任何方法可以禁用该选项卡。 What do you want to do with the MP4 file?您想对 MP4 文件做什么？

Because this WLX plug-in （AppLoader） is used actually making different third-party applications to open video, audio, and picture files based on the file extension, so it does not need to create a new tab, such as opening videos with MPV and using irfanView to open the picture etc., it is equivalent to binding F3's function of "Open with",The [Editor] section of the Apploder.ini file can be binded through the simple editing：

![2023-09-25_211632](https://github.com/tablacus/TablacusExplorerAddons/assets/29940386/8e818953-310e-4e36-8a31-35de20e35025)

I want to know if Tablacus also has such addon. It can customize F3 to bind different types of files to different third -party applications according to different extensions, and can pass parameters?

Apploader.wlx
http://maximus.in.ua/tcplugins/apploader.php?lang=0

**Comment by ccfs** [comment]
You can use "Execution filter" add-on.

Example to bind F3 key to various applications according to file type:
![image](https://github.com/tablacus/TablacusExplorerAddons/assets/34089121/06cce2a4-4760-415f-ac5c-263773404a01)

Example to bind mouse middle button to various applications according to file type:
![image](https://github.com/tablacus/TablacusExplorerAddons/assets/34089121/422cc08d-2da0-4ce0-b422-0c9c3c8177a5)

After you have chosen "Execution filter" as "Type", you can click the Browse button consecutively to input filter (file type), command (usually [Selected items](https://github.com/tablacus/TablacusExplorer/wiki/Type-Selected-items) or [Exec](https://github.com/tablacus/TablacusExplorer/wiki/Type-Exec)) and program path. For "Exec" you have to enter %Selected% which will be replaced by the paths of selected items at use.

Note that, at use, if multiple items are selected, they must be the same type.

---
The screenshot directory problem is probably due to the command line you start MPV. This one works fine for on my computer. The screenshots are saved in the video's directory.

"C:\Portable Apps\mpv\mpv.exe" --screenshot-template=%X{%TEMP%}\%f-%wH%wM%wS

---
"Folder menu list" is the menu shown by "Hot button", isn't it?
Unfortunately, Mouse add-on does not work on the menu.

**Comment by 921j** [comment]
My Bad， I didn't explain the problem clearly！
The built-in screenshot function of MPV is normally saved in the same directory as the opened video file;
But what I use more is another script, mpv_crop_script :
https://github.com/TheAMM/mpv_crop_script
This script can directly capture and cut the video screen, which is very easy to use, Can simplify many steps, but unfortunately it seems that the author no longer maintains it. Maybe it is a problem with this script?
When I configure output_template=Folder.${ext} in mpv_crop_script.conf, the MPV opened is bound to the AppLoader.wlx plug-in under Total Commander can save "Folder.png" Correctly, but not under Tablacus.
Use output_template=${path}. Both are OK, but the file name cannot be changed to the desired "Folder.png". Because I don't understand lua scripts., so I had to find the calling directory of MPV. Currently, I can use it this way, but I can’t hide the CMD window...
![2023-09-27_203320](https://github.com/tablacus/TablacusExplorerAddons/assets/29940386/01d26dec-0b61-43cd-b2c4-acc7c38e13af)



How wonderful it would be  mouse add-on can work on the folder menu list！

**Comment by ccfs** [comment]
When you run a program from TE, the working folder defaults to the program folder. I find only one exception: drag-and-drop items to an EXE file.

I have successfully saved screen crops to their mp4 file folders using these lines in "mpv_crop_script.conf". mpv.exe is started by Type "Exec" or "Execution filter", without cmd.
```
#ok output_template=${path}.png
#ok output_template=${path}\..\folder.png
output_template=${path}\..\folder.${ext}
```

**Comment by 921j** [comment]
Yes！!
This parameter is indeed feasible, thanks! for your patient help! It's very kind of you.

**Comment by ccfs** [comment]
You may be interested in this new add-on [mpv](https://github.com/tablacus/TablacusExplorer/issues/705).
