### ISSUE TITLE
Hide Title bar 1.10 

### ISSUE THREAD

**Issue by shrivatsahosabettu** [tablacus/TablacusExplorerAddons#378]
Hi,

I have installed the Hide Title bar, but there is no way I can move the window or close the window once the title bar is gone. I tried to get back the title bar again, by deleting the Add-on hide titlebar folder installed and reload the window. Not able to recover to the earlier state.

Is there any way?

**Comment by ccfs** [comment]
You can enable "Grab bar" and/or "Grab button" add-on so that you can drag TE window.
Choose Tools > Add-ons and click the Delete button of "Hide Title bar" add-on. The title bar should show again.
Please post some screen captures and your TE info from Help > About in cause you still gets a problem.

**Comment by shrivatsahosabettu** [comment]
Awesome. That works. I didn't new that there is a way to delete like Tools > Add-ons and click the Delete button. I used to go to the folder of Add-ons and delete the folder. Thanks for assisting and bow for your wonderful work.
